language: python

python:
  - 3.7

before_install:
  - env
  - pip install poetry

install:
  - poetry install

script:
  - poetry run pytest --cov=py_de_familia tests/

before_deploy:
  - poetry build

deploy:
  provider: script
  script: poetry publish -u $PYPI_USER -p $PYPI_PASS
  skip_cleanup: true
  on:
#    tags: true
    branch: main

after_success:
  - bash <(curl -s https://codecov.io/bash)
